Revert "Do not include download stage in checksum computation."
This reverts commit 5c26427121fa458947e12143c8684428b13e096e.

I think I get the idea of this patch, but it also removes the
download stage from the build process.  This breaks pristine
builds that include GIT sources.

    12:10:24 janneke@peder:~/tmp
    $ git clone --ref ~/vc/gub github:gub.git
    Initialized empty Git repository in /home/janneke/tmp/gub/.git/
    Checking out files: 100% (497/497), done.
    12:10:35 janneke@peder:~/tmp
    $ cd gub
    12:10:38 janneke@peder:~/tmp/gub
    $ bin/gub --keep tools::fontconfig
    bin/../gub/cross.py:1: DeprecationWarning: the md5 module is deprecated; use hashlib instead
      import md5
    calculating dependencies
     *** Stage: download (make, tools)
    downloading ftp://ftp.gnu.org/pub/gnu/make/make-3.81.tar.gz -> /home/janneke/tmp/gub/downloads/make
    ...............................
    done (1564560)
     *** Stage: download (tar, tools)
    downloading ftp://ftp.gnu.org/pub/gnu/tar/tar-1.20.tar.gz -> /home/janneke/tmp/gub/downloads/tar
    ........................................................
    done (2822777)
     *** Stage: download (libtool, tools)
    downloading ftp://ftp.gnu.org/pub/gnu/libtool/libtool-2.2.6a.tar.gz -> /home/janneke/tmp/gub/downloads/libtool
    .........................................................
    done (2870524)
     *** Stage: download (curl, tools)
    downloading http://curl.haxx.se/download/curl-7.19.0.tar.gz -> /home/janneke/tmp/gub/downloads/curl
    .......................................................
    done (2808891)
     *** Stage: download (m4, tools)
    downloading ftp://ftp.gnu.org/pub/gnu/m4/m4-1.4.12.tar.gz -> /home/janneke/tmp/gub/downloads/m4
    .......................
    done (1168821)
     *** Stage: download (autoconf, tools)
    downloading ftp://ftp.gnu.org/pub/gnu/autoconf/autoconf-2.63.tar.gz -> /home/janneke/tmp/gub/downloads/autoconf
    ...............................
    done (1562665)
     *** Stage: download (patch, tools)
    downloading http://lilypond.org/download/gub-sources/patch-2.5.9-5.tar.gz -> /home/janneke/tmp/gub/downloads/patch
    downloading http://lilypond.org/download/gub-sources/patch/patch-2.5.9-5.tar.gz -> /home/janneke/tmp/gub/downloads/patch
    .....
    done (239546)
     *** Stage: download (zlib, tools)
    downloading http://heanet.dl.sourceforge.net/sourceforge/libpng/zlib-1.2.3.tar.gz -> /home/janneke/tmp/gub/downloads/zlib
    ..........
    done (496597)
     *** Stage: download (freetype, tools)
    downloading http://download.savannah.nongnu.org/releases/freetype/freetype-2.1.10.tar.gz -> /home/janneke/tmp/gub/downloads/freetype
    ............................
    done (1382645)
     *** Stage: download (expat, tools)
    downloading http://surfnet.dl.sourceforge.net/sourceforge/expat/expat-2.0.1.tar.gz -> /home/janneke/tmp/gub/downloads/expat
    .........
    done (446456)
     *** Stage: download (pkg-config, tools)
    downloading http://pkg-config.freedesktop.org/releases/pkg-config-0.20.tar.gz -> /home/janneke/tmp/gub/downloads/pkg-config
    ...................
    done (969993)
     *** Stage: download (bzip2, tools)
    downloading http://www.bzip.org/1.0.5/bzip2-1.0.5.tar.gz -> /home/janneke/tmp/gub/downloads/bzip2
    .................
    done (841402)
     *** Stage: download (git, tools)
    downloading http://kernel.org/pub/software/scm/git/git-1.5.3.6.tar.bz2 -> /home/janneke/tmp/gub/downloads/git
    ...........................
    done (1356739)
     *** Stage: download (fontconfig, tools)
    must rebuild[tools]: librestrict make tar libtool curl m4 autoconf patch zlib freetype expat pkg-config bzip2 git fontconfig
    building package: tools::librestrict
     *** Stage: untar (librestrict, tools)
     *** Stage: patch (librestrict, tools)
     *** Stage: shadow (librestrict, tools)
     *** Stage: compile (librestrict, tools)
     *** Stage: install (librestrict, tools)
     *** Stage: package (librestrict, tools)
     *** Stage: pkg_install (librestrict, tools)

    building package: tools::make
     *** Stage: untar (make, tools)
     *** Stage: patch (make, tools)
     *** Stage: autoupdate (make, tools)
     *** Stage: configure (make, tools)
     *** Stage: compile (make, tools)
     *** Stage: install (make, tools)
     *** Stage: package (make, tools)
     *** Stage: pkg_install (make, tools)

    building package: tools::tar
     *** Stage: untar (tar, tools)
     *** Stage: patch (tar, tools)
     *** Stage: autoupdate (tar, tools)
     *** Stage: configure (tar, tools)
     *** Stage: compile (tar, tools)
     *** Stage: install (tar, tools)
     *** Stage: package (tar, tools)
     *** Stage: pkg_install (tar, tools)

    building package: tools::libtool
     *** Stage: untar (libtool, tools)
     *** Stage: patch (libtool, tools)
     *** Stage: autoupdate (libtool, tools)
     *** Stage: configure (libtool, tools)
     *** Stage: compile (libtool, tools)
     *** Stage: install (libtool, tools)
     *** Stage: package (libtool, tools)
     *** Stage: pkg_install (libtool, tools)

    building package: tools::curl
     *** Stage: untar (curl, tools)
     *** Stage: patch (curl, tools)
     *** Stage: autoupdate (curl, tools)
     *** Stage: configure (curl, tools)
     *** Stage: compile (curl, tools)
     *** Stage: install (curl, tools)
     *** Stage: package (curl, tools)
     *** Stage: pkg_install (curl, tools)

    building package: tools::m4
     *** Stage: untar (m4, tools)
     *** Stage: patch (m4, tools)
     *** Stage: autoupdate (m4, tools)
     *** Stage: configure (m4, tools)
     *** Stage: compile (m4, tools)
     *** Stage: install (m4, tools)
     *** Stage: package (m4, tools)
     *** Stage: pkg_install (m4, tools)

    building package: tools::autoconf
     *** Stage: untar (autoconf, tools)
     *** Stage: patch (autoconf, tools)
     *** Stage: autoupdate (autoconf, tools)
     *** Stage: configure (autoconf, tools)
     *** Stage: compile (autoconf, tools)
     *** Stage: install (autoconf, tools)
     *** Stage: package (autoconf, tools)
     *** Stage: pkg_install (autoconf, tools)

    building package: tools::patch
     *** Stage: untar (patch, tools)
     *** Stage: patch (patch, tools)
     *** Stage: autoupdate (patch, tools)
     *** Stage: configure (patch, tools)
     *** Stage: compile (patch, tools)
     *** Stage: install (patch, tools)
     *** Stage: package (patch, tools)
     *** Stage: pkg_install (patch, tools)

    building package: tools::zlib
     *** Stage: untar (zlib, tools)
     *** Stage: patch (zlib, tools)
     *** Stage: autoupdate (zlib, tools)
     *** Stage: configure (zlib, tools)
     *** Stage: compile (zlib, tools)
     *** Stage: install (zlib, tools)
     *** Stage: package (zlib, tools)
     *** Stage: pkg_install (zlib, tools)

    building package: tools::freetype
     *** Stage: untar (freetype, tools)
     *** Stage: patch (freetype, tools)
     *** Stage: autoupdate (freetype, tools)
     *** Stage: configure (freetype, tools)
     *** Stage: compile (freetype, tools)
     *** Stage: install (freetype, tools)
     *** Stage: package (freetype, tools)
     *** Stage: pkg_install (freetype, tools)

    building package: tools::expat
     *** Stage: untar (expat, tools)
     *** Stage: patch (expat, tools)
     *** Stage: autoupdate (expat, tools)
     *** Stage: configure (expat, tools)
     *** Stage: compile (expat, tools)
     *** Stage: install (expat, tools)
     *** Stage: package (expat, tools)
     *** Stage: pkg_install (expat, tools)

    building package: tools::pkg-config
     *** Stage: untar (pkg-config, tools)
     *** Stage: patch (pkg-config, tools)
     *** Stage: autoupdate (pkg-config, tools)
     *** Stage: configure (pkg-config, tools)
     *** Stage: compile (pkg-config, tools)
     *** Stage: install (pkg-config, tools)
     *** Stage: package (pkg-config, tools)
     *** Stage: pkg_install (pkg-config, tools)

    building package: tools::bzip2
     *** Stage: untar (bzip2, tools)
     *** Stage: patch (bzip2, tools)
     *** Stage: shadow (bzip2, tools)
     *** Stage: compile (bzip2, tools)
     *** Stage: install (bzip2, tools)
     *** Stage: package (bzip2, tools)
     *** Stage: pkg_install (bzip2, tools)

    building package: tools::git
     *** Stage: untar (git, tools)
     *** Stage: patch (git, tools)
     *** Stage: autoupdate (git, tools)
     *** Stage: configure (git, tools)
     *** Stage: compile (git, tools)
     *** Stage: install (git, tools)
     *** Stage: package (git, tools)
     *** Stage: pkg_install (git, tools)

    building package: tools::fontconfig
     *** Stage: untar (fontconfig, tools)
    Command barfed: cd /home/janneke/tmp/gub/downloads/fontconfig && git clone --depth 10 -l -s /home/janneke/tmp/gub/downloads/fontconfig /home/janneke/tmp/gub/target/tools/src/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b

    Tail of target/tools/log/build.log >>>>>>>>
    +bits=32
    +branch=
    +build_architecture=x86_64-linux
    +build_bits=64
    +build_cpu=x86_64
    +build_dependencies_string=expat;freetype;libtool;pkg-config;tools::git;tools::librestrict;tools::make
    +build_hardware_bits=64
    +build_os=linux
    +build_platform=linux-64
    +builddir=/home/janneke/tmp/gub/target/tools/build/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b
    +cache_file=/home/janneke/tmp/gub/target/tools/build/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b/config.cache
    +category=
    +checksum_file=/home/janneke/tmp/gub/target/tools/packages/fontconfig.checksum
    +compile_command=make  -j2  man_MANS= DOCSRC=""
    +configure_binary=/home/janneke/tmp/gub/target/tools/src/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b/configure
    +configure_command=/home/janneke/tmp/gub/target/tools/src/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b/configure --prefix=/home/janneke/tmp/gub/target/tools/install/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b-root/usr --prefix=/home/janneke/tmp/gub/target/tools/root/usr --enable-shared --enable-static  CFLAGS=-I/home/janneke/tmp/gub/target/tools/root/usr/include LDFLAGS=-L/home/janneke/tmp/gub/target/tools/root/usr/lib
    +conflicts_string=;
    +core_prefix=/home/janneke/tmp/gub/target/tools/root/usr/cross/core
    +cpu=tools
    +cpu_count_str=2
    +cross_allsrcdir=/home/janneke/tmp/gub/target/tools/src/cross
    +cross_dir=/cross
    +cross_packages=/home/janneke/tmp/gub/target/tools/packages/cross
    +cross_prefix=/home/janneke/tmp/gub/target/tools/root/usr/cross
    +cross_statusdir=/home/janneke/tmp/gub/target/tools/status/cross
    +debian_branch=unstable
    +dependencies_string=;libtool;freetype;expat;pkg-config
    +description=
    +downloads=/home/janneke/tmp/gub/downloads
    +fakeroot=fakeroot -i -s
    +fakeroot_cache=
    +file_name=fontconfig
    +full_version=0dffe625d43c1165f8b84f97e8ba098793e2cf7b
    +gtk_version=2.8
    +gubdir=/home/janneke/tmp/gub
    +install_command=make man_MANS= DOCSRC=""  DESTDIR=/home/janneke/tmp/gub/target/tools/install/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b-root install
    +install_prefix=/home/janneke/tmp/gub/target/tools/install/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b-root/usr
    +install_root=/home/janneke/tmp/gub/target/tools/install/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b-root
    +installdir=/home/janneke/tmp/gub/target/tools/install
    +logdir=/home/janneke/tmp/gub/target/tools/log
    +makeflags=man_MANS= DOCSRC=""
    +name=fontconfig
    +name_version=fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b
    +native_compile_command=make  -j2
    +nsisdir=/home/janneke/tmp/gub/nsis
    +os=tools
    +package_arch=amd64
    +packages=/home/janneke/tmp/gub/target/tools/packages
    +packaging_suffix_dir=/home/janneke/tmp/gub/target/tools/root
    +patchdir=/home/janneke/tmp/gub/patches
    +platform=tools
    +platform_uploads=/home/janneke/tmp/gub/uploads/tools
    +prefix_dir=/usr
    +pretty_name=Fontconfig
    +root_dir=/root
    +rpath=-Wl,-rpath -Wl,\$$ORIGIN/../lib
    +so_version=1
    +source_checksum=0dffe625d43c1165f8b84f97e8ba098793e2cf7b
    +source_name=fontconfig
    +sourcefiledir=/home/janneke/tmp/gub/sourcefiles
    +specdir=/home/janneke/tmp/gub/gub/specs
    +split_ball=/home/janneke/tmp/gub/target/tools/packages/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b.tools.gup
    +split_hdr=/home/janneke/tmp/gub/target/tools/packages/fontconfig.tools.hdr
    +split_name=fontconfig
    +src_package_ball=/home/janneke/tmp/gub/target/tools/packages/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b-src.tools.tar.gz
    +src_package_uploads=/home/janneke/tmp/gub/target/tools/packages
    +srcdir=/home/janneke/tmp/gub/target/tools/src/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b
    +stamp_file=/home/janneke/tmp/gub/target/tools/status/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b-0dffe625d43c1165f8b84f97e8ba098793e2cf7b
    +statusdir=/home/janneke/tmp/gub/target/tools/status
    +sub_name=
    +system_prefix=/home/janneke/tmp/gub/target/tools/root/usr
    +system_root=/home/janneke/tmp/gub/target/tools/root
    +target_architecture=x86_64-linux
    +target_bits=64
    +target_cpu=x86_64
    +target_gcc_flags=
    +target_os=linux
    +target_platform=tools
    +targetdir=/home/janneke/tmp/gub/target/tools
    +toolchain_prefix=x86_64-linux-
    +tools_prefix=/home/janneke/tmp/gub/target/tools/root/usr
    +tools_root=/home/janneke/tmp/gub/target/tools/root
    +uploads=/home/janneke/tmp/gub/uploads
    +vc_branch=
    +vc_branch_suffix=
    +version=0dffe625d43c1165f8b84f97e8ba098793e2cf7b
    +workdir=/home/janneke/tmp/gub
    +rm -rf /home/janneke/tmp/gub/target/tools/install/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b-root
    +Dump
    +/home/janneke/tmp/gub/target/tools/status/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b-0dffe625d43c1165f8b84f97e8ba098793e2cf7b
    +package
    +rm -rf  /home/janneke/tmp/gub/target/tools/status/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b-0dffe625d43c1165f8b84f97e8ba098793e2cf7b /home/janneke/tmp/gub/target/tools/install/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b-root
    +rm -rf /home/janneke/tmp/gub/target/tools/src/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b /home/janneke/tmp/gub/target/tools/build/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b
    building package: tools::fontconfig
     *** Stage: untar (fontconfig, tools)
    invoking rm -rf /home/janneke/tmp/gub/target/tools/src/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b /home/janneke/tmp/gub/target/tools/build/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b /home/janneke/tmp/gub/target/tools/install/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b-root
    invoking cd /home/janneke/tmp/gub/downloads/fontconfig && git clone --depth 10 -l -s /home/janneke/tmp/gub/downloads/fontconfig /home/janneke/tmp/gub/target/tools/src/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b
    cd: 1: can't cd to /home/janneke/tmp/gub/downloads/fontconfig
    Command barfed: cd /home/janneke/tmp/gub/downloads/fontconfig && git clone --depth 10 -l -s /home/janneke/tmp/gub/downloads/fontconfig /home/janneke/tmp/gub/target/tools/src/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b

    <<<<<<<< Tail of target/tools/log/build.log

    *** Failed target: tools::fontconfig

    Traceback (most recent call last):
      File "bin/gub", line 323, in <module>
	main ()
      File "bin/gub", line 319, in main
	logged_build (settings, options, files)
      File "bin/gub", line 288, in logged_build
	sys.exit (exceptional_build (settings, options, files, logger))
      File "bin/gub", line 267, in exceptional_build
	build (settings, options, files)
      File "bin/gub", line 263, in build
	b.build_source_packages (names)
      File "bin/../gub/buildrunner.py", line 286, in build_source_packages
	self.spec_build (spec_name)
      File "bin/../gub/buildrunner.py", line 233, in spec_build
	deferred_runner.execute_deferred_commands ()
      File "bin/../gub/runner.py", line 161, in execute_deferred_commands
	cmd.execute (self.logger)
      File "bin/../gub/commands.py", line 48, in execute
	buildspec.source.update_workdir (buildspec.expand ('%(srcdir)s'))
      File "bin/../gub/repository.py", line 637, in update_workdir
	self.git ('clone --depth 10 -l -s %(checkout_dir)s %(destdir)s' % locals ())
      File "bin/../gub/repository.py", line 556, in git
	ignore_errors=ignore_errors, env=self.get_env ())
      File "bin/../gub/repository.py", line 186, in logged
	return loggedos_func (self.logger, *args, **kwargs)
      File "bin/../gub/loggedos.py", line 28, in system
	raise misc.SystemFailed (m)
    gub.misc.SystemFailed: Command barfed: cd /home/janneke/tmp/gub/downloads/fontconfig && git clone --depth 10 -l -s /home/janneke/tmp/gub/downloads/fontconfig /home/janneke/tmp/gub/target/tools/src/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b

    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/dist-packages/apport_python_hook.py", line 38, in apport_excepthook
	from apport.packaging_impl import impl as packaging
      File "/usr/lib/python2.6/dist-packages/apport/__init__.py", line 1, in <module>
	from apport.report import Report
      File "/usr/lib/python2.6/dist-packages/apport/report.py", line 20, in <module>
	from problem_report import ProblemReport
      File "/usr/lib/python2.6/dist-packages/problem_report.py", line 15, in <module>
	import zlib, base64, time, UserDict, sys, gzip, struct
      File "/usr/lib/python2.6/gzip.py", line 35, in <module>
	class GzipFile:
      File "/usr/lib/python2.6/gzip.py", line 332, in GzipFile
	def flush(self,zlib_mode=zlib.Z_SYNC_FLUSH):
    AttributeError: 'module' object has no attribute 'Z_SYNC_FLUSH'

    Original exception was:
    Traceback (most recent call last):
      File "bin/gub", line 323, in <module>
	main ()
      File "bin/gub", line 319, in main
	logged_build (settings, options, files)
      File "bin/gub", line 288, in logged_build
	sys.exit (exceptional_build (settings, options, files, logger))
      File "bin/gub", line 267, in exceptional_build
	build (settings, options, files)
      File "bin/gub", line 263, in build
	b.build_source_packages (names)
      File "bin/../gub/buildrunner.py", line 286, in build_source_packages
	self.spec_build (spec_name)
      File "bin/../gub/buildrunner.py", line 233, in spec_build
	deferred_runner.execute_deferred_commands ()
      File "bin/../gub/runner.py", line 161, in execute_deferred_commands
	cmd.execute (self.logger)
      File "bin/../gub/commands.py", line 48, in execute
	buildspec.source.update_workdir (buildspec.expand ('%(srcdir)s'))
      File "bin/../gub/repository.py", line 637, in update_workdir
	self.git ('clone --depth 10 -l -s %(checkout_dir)s %(destdir)s' % locals ())
      File "bin/../gub/repository.py", line 556, in git
	ignore_errors=ignore_errors, env=self.get_env ())
      File "bin/../gub/repository.py", line 186, in logged
	return loggedos_func (self.logger, *args, **kwargs)
      File "bin/../gub/loggedos.py", line 28, in system
	raise misc.SystemFailed (m)
    gub.misc.SystemFailed: Command barfed: cd /home/janneke/tmp/gub/downloads/fontconfig && git clone --depth 10 -l -s /home/janneke/tmp/gub/downloads/fontconfig /home/janneke/tmp/gub/target/tools/src/fontconfig-0dffe625d43c1165f8b84f97e8ba098793e2cf7b

    [1]12:16:46 janneke@peder:~/tmp/gub
    $