tools::gmp: compile without stack protector.  May fix some guile builds.
Also eliminated are __isoc99_fscanf and friends from glibc2.7.  I fail
to see why having these is a problem, tools are being run against
/lib/libc6 which has those symbols anyway, right?  What am I missing,
a newer libc in /usr/local that is being accessed with LD_LIBRARY_PATH?
    
     in linux-x86::guile     /main/src/gub/target/tools/root/usr/lib/libgmp.so: undefined reference to `__stack_chk_fail@GLIBC_2.4'