OpenOffice: Add missing fixes for fresh build.
It now reaches

**************************************************
ERROR: ERROR: Could not register all components for file services.rdb (gid_Starregistry_Services_Rdb)!
in function: create_services_rdb
**************************************************

**************************************************
ERROR: Saved logfile: /home/janneke/vc/gub/target/mingw/build/openoffice-trunk/build/ooo300-m9/instsetoo_native/util/OpenOffice//logging/en-US/log_OOO300_en-US.log
**************************************************
... cleaning the output tree ...
... removing directory /home/janneke/vc/gub/target/mingw/build/openoffice-trunk/build/ooo300-m9/instsetoo_native/util/OpenOffice//zip/en-US ...
... removing directory /home/janneke/vc/gub/target/mingw/build/openoffice-trunk/build/ooo300-m9/instsetoo_native/util/OpenOffice//gid_Starregistry_Services_Rdb_servicesrdb/en-US_witherror_1 ...
Tue Feb 17 18:03:15 2009 (01:09 min.)
Failed to install:  at ./ooinstall line 143.
make: *** [install] Error 1